version: 2​
jobs:​
  build:​
    docker:​
      - image: circleci/python:3.7.1
    working_directory: ~/Python-AQA-course

    steps:​
      - checkout​
      - run:​
          name: install dependencies​
          command: |​
           python3 -m venv venv​
            . venv/bin/activate​
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
            pytest tests/

      -store_artifacts:
          path: test_reports
          destination: test_reports
