version: 2​
jobs:​
  build:​
    docker:​
      - image: circleci/python:3.7.1-stretch-node-browsers
    working_directory: ~/Python-AQA-course

    steps:​
      - checkout​
      - run:​
          name: install dependencies​
          command: |​
           python3 -m venv venv​
            . venv/bin/activate​
            pip install -r requirements.txt
